# compose를 통해 실행할 서비스들을 정의
services:
  # compose으로 묶인 하위 컨테이너들
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    #    environment:
    #      MYSQL_DATABASE: ${DB_NAME}
    #      MYSQL_USER: ${DB_USER}
    #      MYSQL_PASSWORD: ${DB_PASSWORD}
    #      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    env_file:
      - .env
    networks:
      - backend-net
    # depends_on: ...
    # restart: ...
volumes:
  mysql-data:

networks:
  backend-net: