services:
  app:
    restart: always

  db:
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-net
