# 공통 베이스 (포트 개방 없음)
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    # DB 활성화 지연으로 인한 JPA 실패로 인한 구동 실패를 방지
    depends_on:
      - db
    environment:
      SPRING_SERVER_PORT: 8080
      APP_MESSAGE: ${APP_MESSAGE}
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${DB_CONNECTION_TIMEOUT}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DB_DDL_AUTO}
    networks:
      - app-net
  db:
    image: mysql:8.0
    # 외부 또는 이미 도커에 빌드 되어 있는 이미지를 사용
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net: