events {
    worker_connections 1024;
}

# http <- 웹 접속
http {
    server {
        # 컨테이너에서 듣는 포트 != 호스트에서 제공하는 포트
        listen 80;

        # 연결하려는 주소(라우트) 기준을 잡아줌
        location / {
            # 내부에서 다른 곳으로 연결 (리버스 프록시, 포트가 변경되면 포트 포워딩)
            # proxy_pass http://locahost:8080;
            proxy_pass http://app1:8080;
            # header 설정
            proxy_set_header Host$host;
            proxy_set_header X-Real-IP$remote_addr;
            proxy_set_header X-Forwarded-For$proxy_add_x_forwarded_for;
        }
    }
}